### PR TITLE
Add Jacky's Bayesian A/B testing into Uplift report

### PR DESCRIPTION
**Pull request by rshkarin**

### CODE REVIEW

**Comment by gburanov** [comment]
@rshkarin  when u look at the diff - it is more then 2000 lines.  Can u point the most important places one should look at?

**Comment by rshkarin** [comment]
@gburanov the changes start from the line 788, however, the review is better to do by opening the notebook with either a local Jupyter server or a Colab environment, since the notebook contains a lot of formatting code, which is required to correctly display the code in notebook's cells.

**Review by dynamix — CHANGES_REQUESTED** [review]
- imports should all happen in on place
- top level code that is related to the Baysian testing should be properly guarded by `run_bayesian_analysis` but currently only the import statements are
- function definitions should be before top level code
- documentation is missing (in the summary in the beginning but for the steps as well) 

And more fundamentally (@jackyckma @rshkarin) why do we need a monte carlo simulation in the first place? Maybe I don't really understand it but shouldn't a exact solution based on https://en.wikipedia.org/wiki/Conjugate_prior#Example be possible for our A/B test @ conversions?

**Comment by jackyckma** [comment]
@dynamix for A/B test on number of conversions, we can use the exact solution based on Conjugate prior. But It is not applicable when we also want to compare the revenue in test and control group.

**Comment by VOvchinnikov** [comment]
@rshkarin @olgen If this PR is still actual, then it should be rebuilt and rebased onto the current master, and code changes moved from pure notebook into the (more GitHub-friendly) .py files.

If it is _not_ actual anymore, can we please close it then, for it not to hand in "Waiting for review" column anymore?

**Comment by rshkarin** [comment]
@VOvchinnikov agree it makes sense just close it if it's not useful anymore. @olgen should this approach be replaced by Alfred's one?

**Pull request closed without merging**
